### ISSUE TITLE
Error when use rotate function

### ISSUE THREAD

**Issue by yamin90** [idecardo/vue-croppie#1]
ReferenceError: copy is not defined
copy = null;

**Comment by idecardo** [comment]
Hi @yamin90 can you please share more details?

**Comment by yamin90** [comment]
<img width="825" alt="screenshot 2019-01-09 at 9 43 24 am" src="https://user-images.githubusercontent.com/33482681/50870512-4c530280-13f3-11e9-91fc-56f846235e02.png">
<img width="565" alt="screenshot 2019-01-09 at 9 43 37 am" src="https://user-images.githubusercontent.com/33482681/50870513-4ceb9900-13f3-11e9-9fff-c461eb7e1ed7.png">
when i use the rotate  refs `this.$refs.croppie.rotate(degrees)` it give an error in the console

**Comment by idecardo** [comment]
Hi @yamin90 looks like it is a bug within the [core](https://github.com/Foliotek/Croppie/issues/570) plugin itself.
